### ISSUE TITLE
computeFling(); error

### ISSUE THREAD

**Issue by ahmerafzal1** [barteksc/AndroidPdfViewer#323]
I'm facing this 

> Error:(548, 25) error: cannot find symbol method computeFling()

`animationManager.computeFling();`

error. Please solve it

**Comment by barteksc** [comment]
When do you see this error? How do you include library?

**Comment by ahmerafzal1** [comment]
When I'm coping you code and put into my code and upgrade 1.6.0 to 1.6.1, after upgrade to 1.6.1 I'm try to downgrade 1.6.0 but problem was same.

**Comment by barteksc** [comment]
So you copy part of source code and want me to solve it? If you want to do it this way, you have to copy all files with dependencies

**Comment by ahmerafzal1** [comment]
Thanks I'm fixed

**Comment by ahmerafzal1** [comment]
Thanks I'm fixed
